url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Gato Polilla"
defaults:
  - scope:
      path: "assets/img/gallery"
    values:
      gallery: true
  - scope:
      path: "assets/img/servicios"
    values:
      services: true
  - scope:
      path: "assets/img/locaciones"
    values:
      locations: true
  - scope:
      path: "assets/img/carousel"
    values:
      carousel: true